schema_version: 1

context:
  python_min: "3.12"
  name: conda-forge-tick
  version: "2026.9.72"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/conda-forge/conda-forge-bot/archive/refs/tags/${{ version }}.tar.gz
  sha256: 84b49900c0ffece68e0f77349ed4b79dde32e54c515d28ea4cb5b73df0b9c991

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - conda-forge-tick = conda_forge_tick.cli:main
      - conda-forge-tick-container = conda_forge_tick.container_cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm >=8
  run:
    - python >=${{ python_min }}
    - backoff
    - bcrypt
    - cachecontrol
    - cachetools
    - click
    - conda >=26
    - conda-build >=26
    - conda-forge-feedstock-ops >=0.20.0
    - conda-forge-metadata >=2026.9.5
    - conda-forge-pinning
    - conda-libmamba-solver
    - conda-lock
    - conda-package-handling
    - conda-recipe-manager >=0.10.6
    - conda-smithy >=2026.5.29
    - curl
    - dateparser
    - distributed
    - feedparser
    - frozendict
    - git !=2.50
    - github3.py
    - grayskull >=3.1.1
    - jinja2
    - lockfile
    - mamba >=0.23
    - msgpack-python
    - networkx >=2.8.6
    - orjson
    - packaging
    - psutil
    - py-rattler >=0.22.0,<0.26.0a0
    - pydantic >=2.13
    - pydantic-extra-types
    - pydantic-settings >=2.15
    - pygithub
    - pymongo
    - pynamodb
    - python-dateutil
    - python-graphviz
    - rattler-build >=0.74,<0.76.0a0
    - rattler-build-conda-compat >=1.4.13,<2
    - requests
    - ruamel.yaml
    - ruamel.yaml.jinja2
    - scipy
    - setuptools
    - stopit
    - streamz
    - tar
    - tqdm
    - wget
    - wurlitzer

tests:
  - python:
      imports:
        - conda_forge_tick
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - python -c "import conda_forge_tick; assert conda_forge_tick.__version__ == '${{ version }}'"
      - conda-forge-tick --help
      - conda-forge-tick-container --help

about:
  summary: Flagship repo for conda-forge-bot
  license: BSD-3-Clause AND MIT
  license_file: License
  homepage: https://github.com/conda-forge/conda-forge-bot

extra:
  recipe-maintainers:
    - beckermr
    - regro-cf-autotick-bot  # bot account controlled by the bot team
