schema_version: 1

context:
  python_min: "3.12"
  name: conda-forge-tick
  version: "2026.9.32"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/conda-forge/conda-forge-bot/archive/refs/tags/${{ version }}.tar.gz
  sha256: 8edd69c711bb072d5c6eb1c246896e402907282ff195457207f72001a4feebe0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - conda-forge-tick = conda_forge_tick.cli:main
      - conda-forge-tick-container = conda_forge_tick.container_cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm >=8
  run:
    - python >=${{ python_min }}
    - attrs
    - backoff
    - bcrypt
    - cachecontrol
    - cachetools
    - click
    - conda >=25
    - conda-lock
    - conda-forge-pinning
    - conda-libmamba-solver
    - conda-forge-metadata >=0.12.0
    - conda-forge-feedstock-ops >=0.16.0
    - conda-recipe-manager >=0.6.1
    - conda-package-handling
    - conda-smithy >=3.61.2
    - conda-build >=25
    - curl
    - dateparser
    - depfinder
    - distributed
    - feedparser
    - frozendict
    - git
    - github3.py
    - grayskull >=3.1.0
    - jinja2
    - lockfile
    - mamba >=0.23
    - msgpack-python
    - networkx !=2.8.1
    - numpy
    - orjson
    - packaging
    - psutil
    - pydantic
    - pydantic-extra-types
    - pydantic-settings
    - pygithub
    - pymongo
    - pynamodb
    - python-dateutil
    - python-graphviz
    - rattler-build >=0.35.4
    - rattler-build-conda-compat >=1.4.6,<2,!=1.4.7,!=1.4.8
    - requests
    - ruamel.yaml
    - ruamel.yaml.jinja2
    - scipy
    - stopit
    - streamz
    - tar
    - tqdm
    - wget
    - wurlitzer
    - yaml

tests:
  - python:
      imports:
        - conda_forge_tick
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - python -c "import conda_forge_tick; assert conda_forge_tick.__version__ == '${{ version }}'"
      - conda-forge-tick --help
      - conda-forge-tick-container --help

about:
  summary: Flagship repo for conda-forge-bot
  license: BSD-3-Clause AND MIT
  license_file: License
  homepage: https://github.com/conda-forge/conda-forge-bot

extra:
  recipe-maintainers:
    - beckermr
    - regro-cf-autotick-bot  # bot account controlled by the bot team
