github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  version_updates:
    random_fraction_to_keep: 0.10
  automerge: true
conda_build_tool: rattler-build
